from lattica_query.auth import get_demo_token

import sys
import pickle

import submission_utils


ACCESS_TOKENS = [
    "",
    "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlIwRTR5Ujd2RnFNSW9ESTBrdGVlayJ9.eyJ0b2tlbklkIjoiMzA5YWMxNTYtMzYwYy00OGMzLTkzOTEtMTEyM2EyNmY3ZWM5IiwiaXNzIjoiaHR0cHM6Ly9sYXR0aWNhLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJtUWFORWR6R1pVd1o1TDVRSjlrNTFVOG91TjRHOTJicEBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9teWFwaS9hcGkiLCJpYXQiOjE3NzE4NDY1OTAsImV4cCI6MTc3NDQzODU5MCwic2NvcGUiOiJ1c2VyIGRlZmF1bHQiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMiLCJhenAiOiJtUWFORWR6R1pVd1o1TDVRSjlrNTFVOG91TjRHOTJicCIsInBlcm1pc3Npb25zIjpbInVzZXIiLCJkZWZhdWx0Il19.HSnlT-bCdStXFEQ8gMaasffFPtG78F8PZXEQWtZofnjjN1AgDA0r_hwuOv55Y99LoRrXDfGvKo0UFz7ongZnixWebayPEpMse05yx1xYT8rkBYtHl_WlXJP8YqDaVSKWD2tBN9psvG40Llx-xff17Rq5eZdjMFf_rhYD0fHVTlt1YMiuIM4ygCdUU4kVC-2uCLm2GTvWEahDMuI6TDIajX0rpmpKJifmx2Cq-V_ZnDQkzMY1K7eJ2fDxGAyHzXrp8f-DsC-a98WeXuoJuJkf-hSk7KGxECyDzycMKaZNMKTjvfLxwisqV93mwsRGeIFdvC7zEtY93VXEoxxEO4HDHg",
    "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlIwRTR5Ujd2RnFNSW9ESTBrdGVlayJ9.eyJ0b2tlbklkIjoiN2I2ZTIwN2MtMDVkYS00NGQ2LWIzZjktZThkNWRjYmI1ZjhmIiwiaXNzIjoiaHR0cHM6Ly9sYXR0aWNhLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJtUWFORWR6R1pVd1o1TDVRSjlrNTFVOG91TjRHOTJicEBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9teWFwaS9hcGkiLCJpYXQiOjE3NzE4NDcyMjgsImV4cCI6MTc3NDQzOTIyOCwic2NvcGUiOiJ1c2VyIGRlZmF1bHQiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMiLCJhenAiOiJtUWFORWR6R1pVd1o1TDVRSjlrNTFVOG91TjRHOTJicCIsInBlcm1pc3Npb25zIjpbInVzZXIiLCJkZWZhdWx0Il19.lpvZX0OotZbzWpF71celkItUUH4dwOc1VWd5MuHO3lapcT_2krlEcuvtJslTTTnWB8-vqOJFdxoY-cpumGg2LfbkGHaBXmBQnguvwv3wtPbc2ROMC9XcK9dgDZTAeKvP5uhiLjkU5zWyH_HxW-fOwFBSZ1YB2HTt6f-2c8eKEsW1ZWoOPux7DIhACQAtyWI0Q_hma61NbhppYRdDBhT83rzmZJm9-iTW_Q_Ihg3fBA9mhbHhSTbvUvyU36ziKgkNASVXNEnJHQf_hVG01rWMjltHrbJ_CcoDzHCBgxH424bwhaVVOxNeXfXfU03_LVf4gCVvVgaa1-DjrN-RED5Jgw",
    "",
]

size = int(sys.argv[1])
local_file_paths = submission_utils.init(size)

# Get access_token for public model
pickle.dump(ACCESS_TOKENS[size], open(local_file_paths.PATH_ACCESS_TOKEN, "wb"))

# Get encryption params and model metadata from BE
client = submission_utils.get_lattica_client(local_file_paths)
context, hom_seq = client.get_init_data()

# Save data to local file system
pickle.dump(context, open(local_file_paths.PATH_CONTEXT, "wb"))
pickle.dump(hom_seq, open(local_file_paths.PATH_HOM_SEQ, "wb"))
